services:
  backend:
    build:
      context: ./backend
    container_name: authnest-backend
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: authnest-frontend
    ports:
      - "5173:80"
    restart: unless-stopped
    depends_on:
      - backend
